version: '3'

services:
  web:
    image: concourse/dev:${CONCOURSE_DEV_TAG}
    volumes: ["${CONCOURSE_KEYS}:/concourse-keys"]

  worker:
    image: concourse/dev:${CONCOURSE_DEV_TAG}
    volumes: ["${CONCOURSE_KEYS}:/concourse-keys"]
