platform: linux

inputs:
- name: backup-tarball

outputs:
- name: ops-files

run:
  path: /bin/bash
  args:
  - -exc
  - |
    tar xvf ./backup-tarball/prod-db-backup.tar

    cat > ops-files/prod-version.yml <<EOF
    - type: replace
      path: /releases/name=concourse
      value:
        name: concourse
        version: $(cat bbr_artifacts/concourse_version | sed 's/^concourse\///' | head -n 1)
    EOF
