platform: linux

params:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:
  BOSH_ENVIRONMENT:

inputs:
- name: ci
- name: bbr-cli
- name: bosh-cli
- name: backup-tarball

run:
  path: ci/tasks/scripts/bbr-restore.sh
