platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/oci-build-task}

params:
  DOCKERFILE: ci/dockerfiles/resource-types/Dockerfile
  REPOSITORY: concourse/dev

inputs:
- name: ci
- name: bosh-io-release-resource
- name: bosh-io-stemcell-resource
- name: cf-resource
- name: docker-image-resource
- name: git-resource
- name: github-release-resource
- name: hg-resource
- name: mock-resource
- name: pool-resource
- name: registry-image-resource
- name: s3-resource
- name: semver-resource
- name: time-resource
- name: tracker-resource

outputs:
- name: image

run:
  path: sh
  args:
  - -c
  - |
    set -euo pipefail

    for resource in $(ls | grep resource); do
        echo repacking ${resource}
        cd ${resource}
            mv metadata.json resource_metadata.json
            tar czf rootfs.tgz --directory=rootfs/ .
            rm -rf ./rootfs/
        cd -
    done;

    build
