---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/builder}

params:
  REPOSITORY: concourse/dev
  DOCKERFILE: ci/dockerfiles/dev/Dockerfile
  IMAGE_ARG_base_image: golang-builder-image/image.tar

inputs:
- name: ci
- name: dumb-init
- name: concourse
- name: gdn
- name: golang-builder-image
- name: containerd
  optional: true
- name: runc
  optional: true
- name: cni
  optional: true
- name: resource-types-image
- name: fly-linux
- name: fly-windows
- name: fly-darwin

outputs:
- name: image

caches:
- path: cache

run: {path: build}
