---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/btrfs-tools-ci

inputs:
- name: concourse

outputs:
- name: btrfs-tools

run:
  path: concourse/ci/tasks/scripts/build-btrfs-tools
