---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/btrfs-tools-ci

inputs:
- name: concourse
- name: ci 

outputs:
- name: btrfs-tools

run:
  path: ci/tasks/scripts/build-btrfs-tools
