---
platform: linux

params:
  REPOSITORY: concourse/golang-builder
  DOCKERFILE: ci/dockerfiles/golang-builder/Dockerfile
  CONTEXT: .

inputs:
- name: concourse
- name: ci
- name: golang-linux

outputs:
- name: image

caches:
- path: cache

run:
  path: build
