---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: release-notes
- name: version
- name: ci

outputs:
- name: built-notes

run:
  path: ci/tasks/scripts/build-prerelease-notes
