---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse-chart-dev
- name: concourse-release
- name: ci

outputs:
- name: concourse-chart-dev

run:
  path: ci/tasks/scripts/bump-chart-app-version
