---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse-chart
- name: version
- name: ci

outputs:
- name: concourse-chart
  path: concourse

run:
  path: ci/tasks/scripts/bump-chart-version
