---
platform: darwin

inputs:
- name: concourse
- name: ci
- name: version
  optional: true
- name: final-version
  optional: true
- name: fly-linux
  optional: true
- name: fly-windows
  optional: true
- name: fly-darwin
  optional: true

outputs:
- name: concourse-darwin

caches:
- path: gopath

run:
  path: ci/tasks/scripts/concourse-build
  args: [darwin]
