platform: linux
inputs:
- name: ci
- name: concourse-release-final
- name: gcp-xenial-stemcell
- name: version
outputs:
- name: product
image_resource:
  type: registry-image
  source: { repository: ubuntu }
params:
  END_OF_GENERAL_SUPPORT:
run:
  path: ci/tasks/scripts/create-pivnet-metadata
