---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
  - name: ci
  - name: concourse-dex

outputs:
  - name: concourse-dex-tag

run:
  path: ci/tasks/scripts/create-dex-merged-tag
