---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

params:
  SUFFIX:

inputs:
- name: ci
- name: version
- name: latest-version
- name: latest-of-same-major-version

outputs:
- name: tags

run:
  path: bash
  args:
  - -c
  - |
    go get -d -v ./...
    go run ci/tasks/scripts/docker-semver-tags/docker_semver_tags.go \
      --shipit=version/version \
      --latest=latest-version/version \
      --latest-of-same-major=latest-of-same-major-version/version \
      --output=tags/tags

