---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse
- name: ci
- name: dev-image
  optional: true
- name: postgres-image
- name: postgres-image-legacy
  optional: true

caches:
- path: gopath

params:
  BUILD:
  CONTAINERD:
  DOWNLOAD_CLI: true
  HAS_RUNTIME_FLAG: true
  POSTGRES_IMAGE: postgres-image

run:
  path: ci/tasks/scripts/pass-release-notes-only-change
  args:
  - ci/tasks/scripts/with-docker-compose
  - ci/tasks/scripts/testflight
