---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse
- name: ci
- name: dev-image
- name: postgres-image
- name: postgres-image-legacy
  optional: true

caches:
- path: gopath

params:
  RUNTIME: guardian
  DOWNLOAD_CLI: true
  HAS_RUNTIME_FLAG: true
  POSTGRES_IMAGE: postgres-image

run:
  path: ci/tasks/scripts/with-docker-compose
  args: [ci/tasks/scripts/testflight]
