---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: node
    tag: 12.7.0-alpine

params:
  GITHUB_TOKEN: ((concourse_github_dummy.access_token))
  SLACK_TOKEN: ((slack_token))

inputs:
- name: ci
- name: src

outputs:
- name: message

run:
  path: ci/tasks/scripts/format-slack-message
