---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: node
    tag: 12.7.0-alpine

params:
  GITHUB_TOKEN:
  SLACK_TOKEN:
  GITHUB_REPO: concourse

inputs:
- name: ci
- name: src

outputs:
- name: message

run:
  path: ci/tasks/scripts/format-slack-message
