---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

inputs:
- name: concourse
- name: ci

caches:
- path: gopath
- path: old-ref

run:
  path: ci/tasks/scripts/golang-lint
