---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/dev}

inputs:
- name: ci

outputs:
- name: linux-dependencies

run:
  path: ci/tasks/scripts/hoist-linux-dependencies
