---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/dev}

inputs:
- name: concourse
- name: ci

outputs:
- name: gdn
- name: resource-types

run:
  path: ci/tasks/scripts/hoist-linux-dependencies
