---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/git-resource

inputs:
- name: concourse
- name: from-commit
- name: to-commit

outputs:
- name: message

params:
  HEADING:

run:
  path: concourse/ci/tasks/scripts/issues-for-commit-range
