---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

params:
  CONCOURSE_IMAGE:
  KUBE_CONFIG:
  RELEASE_NAME:
  VALUES:

inputs:
- name: charts
- name: ci
- name: concourse
- name: image-info
- name: values
  optional: true

run:
  path: ci/tasks/scripts/k8s-deploy
