---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse
- name: ci
- name: concourse-rc-image
- name: concourse-chart
- name: prometheus-chart
- name: postgresql-chart

caches:
- path: gopath

params:
  CONCOURSE_CHART_DIR:
  CONCOURSE_IMAGE_NAME:
  KUBE_CONFIG:
  HELM_VERSION: 3

run:
  path: ci/tasks/scripts/k8s-topgun
