---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

inputs:
- name: chart-pr
- name: concourse-chart
- name: ci

run:
  path: bash
  args:
  - -cex
  - |
    go get -d -v ./...
    go run ci/tasks/scripts/k8s-version-bump-check.go
