---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

params:
  CONCOURSE_CHART_DIR:
  CONCOURSE_IMAGE_NAME:
  KUBE_CONFIG:

inputs:
- name: concourse
- name: ci
- name: concourse-rc-image
- name: concourse-chart
- name: helm-charts

caches:
- path: gopath

run:
  path: ci/tasks/scripts/k8s-topgun
