---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

params:
  KUBE_CONFIG:
  RELEASE_NAME:
  MAX_TICKS: 180

inputs:
- name: ci
- name: concourse
- name: values

caches:
- path: gopath
- path: concourse/web/wats/node_modules

run:
  path: ci/tasks/scripts/k8s-smoke
