---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/wats-ci

params:
  ATC_URL: ~

inputs:
- name: concourse
- name: ci

caches:
- path: gems
- path: concourse/pkg

run:
  path: ci/tasks/scripts/lengthy-output
