---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse-chart
- name: chart-repo-index
- name: concourse-version
- name: ci

outputs:
- name: packaged-chart
- name: concourse

run:
  path: ci/tasks/scripts/package-chart
