---
platform: linux

image_resource:
  type: registry-image
  source: {repository: alpine}

params:
  ADMIN_USERNAME:
  ADMIN_PASSWORD:
  CONCOURSE_URL:

inputs:
- name: ci

run:
  path: ci/tasks/scripts/reconfigure-teams

