platform: linux
image_resource:
  type: registry-image
  source:
    repository: k14s/image
    # does not publish a 'latest' tag currently
    tag: kbld-rand-1592942790507001000-1148625018150
inputs:
- name: pipelines
outputs:
- name: rendered_pipelines
params:
  RESOURCES:
run:
  path: pipelines/tasks/scripts/render-resource-pipeline-templates
  user: root
