platform: linux
image_resource:
  type: registry-image
  source:
    repository: k14s/image
    # does not publish a 'latest' tag currently
    tag: kbld-rand-1592942790507001000-1148625018150
inputs:
- name: pipelines
- name: pipelines-and-tasks
outputs:
- name: rendered_pipelines
params:
  PIPELINES:
run:
  path: pipelines-and-tasks/tasks/scripts/render-ytt-templates
  user: root
