---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: full

params:
  GCP_PROJECT:
  GCP_KEY:
  WORKSPACE: default

inputs:
- name: ci

outputs:
- name: cloud-config

run:
  path: ci/tasks/scripts/terraform-branch-env
