---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

params:
  GCP_PROJECT:
  GCP_KEY:
  SSH_KEY:
  WORKSPACE: default
  CONCOURSE_VERSION: "dev"
  # variables consumed by terraform and their default values
  # TF_VAR_ENABLE_CONTAINERD: "false"
  # TF_VAR_HAS_RUNTIME_FLAG: "true"

inputs:
- name: concourse
- name: ci
- name: packer-image
  optional: true
- name: linux-rc
  optional: true

outputs:
- name: outputs

run:
  path: ci/tasks/scripts/terraform-smoke
