---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse
- name: dev-image
  optional: true
- name: concourse-image
  optional: true
- name: postgres-image
  optional: true

run:
  path: concourse/ci/tasks/scripts/upgrade-test
