#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("@ytt:assert", "assert")

#@ resource_name = data.values.resource_name or assert.fail("resource name must be specified")

#@ def build_params(resource_name):
  #@ if resource_name == "registry-image":
CONTEXT: #@ resource_name + "-resource"
BUILD_ARG_DOCKER_PRIVATE_PASSWORD: ((registry_image_resource_docker.password))
BUILD_ARG_DOCKER_PRIVATE_REPO: ((registry_image_resource_docker.private_repo))
BUILD_ARG_DOCKER_PRIVATE_USERNAME: ((registry_image_resource_docker.username))
BUILD_ARG_DOCKER_PUSH_PASSWORD: ((registry_image_resource_docker.password))
BUILD_ARG_DOCKER_PUSH_REPO: ((registry_image_resource_docker.push_repo))
BUILD_ARG_DOCKER_PUSH_USERNAME: ((registry_image_resource_docker.username))
  #@ elif resource_name == "semver":
CONTEXT: #@ resource_name + "-resource"
BUILD_ARG_SEMVER_TESTING_ACCESS_KEY_ID: ((semver_resource_bucket.access_key))
BUILD_ARG_SEMVER_TESTING_BUCKET: ((semver_resource.bucket))
BUILD_ARG_SEMVER_TESTING_REGION: ((semver_resource.region))
BUILD_ARG_SEMVER_TESTING_SECRET_ACCESS_KEY: ((semver_resource_bucket.secret_key))
  #@ elif resource_name == "s3":
CONTEXT: #@ resource_name + "-resource"
BUILD_ARG_S3_TESTING_ACCESS_KEY_ID: ((s3_resource_bucket.access_key))
BUILD_ARG_S3_TESTING_SECRET_ACCESS_KEY: ((s3_resource_bucket.secret_key))
BUILD_ARG_S3_TESTING_BUCKET: ((s3_resource.bucket))
BUILD_ARG_S3_VERSIONED_TESTING_BUCKET: ((s3_resource.versioned_bucket))
BUILD_ARG_S3_TESTING_REGION: ((s3_resource.region))
BUILD_ARG_S3_ENDPOINT: https://s3.amazonaws.com
  #@ elif resource_name == "concourse-pipeline":
CONTEXT: .
  #@ elif resource_name == "docker-image":
CONTEXT: #@ resource_name + "-resource"
UNPACK_ROOTFS: 'true'
  #@ else:
CONTEXT: #@ resource_name + "-resource"
  #@ end
#@ end

#@ def build_task(resource_name, distro):
task: build
privileged: true
image: oci-build-task
config:
  platform: linux
  inputs:
  - name: #@ resource_name + "-resource"
  outputs:
  - name: built-resource-image
    path: image
  params:
    DOCKERFILE: #@ resource_name + "-resource/dockerfiles/" + distro + "/Dockerfile"
    _: #@ template.replace(build_params(resource_name))
    #! TODO: use pre-fetched base image once the build task supports it,
    #! i.e. load_base: #@ determine_base(distro)
  run: {path: build}
#@ end

#@ def build_image(distro):
name: #@ "build-" + distro
plan:
- in_parallel:
  - get: #@ resource_name + "-resource"
    resource: resource-repo
    trigger: true
  - get: #@ determine_base(distro)
    trigger: true
    params: {format: oci}
  - get: oci-build-task
  - #@ template.replace(extra_get_steps(distro))
- #@ build_task(resource_name, distro)
- #@ template.replace(extra_steps(distro))
- put: #@ "resource-image-dev-" + distro
  params: {image: built-resource-image/image.tar}
#@ end

#@ def extra_steps(distro):
  #@ if resource_name == "docker-image":
- task: smoke-test
  image: built-resource-image
  file: docker-image-resource/ci/smoke-test.yml
  privileged: true
  params:
    REPOSITORY: busybox
  output_mapping:
    fetched-image: busybox
- task: use-fetched-image
  image: busybox
  config:
    platform: linux
    run:
      path: /bin/true
  #@ else: return []
#@ end

#@ def determine_base(distro):
#@ if distro == "alpine":
#@   return "alpine-edge"
#@ elif distro == "ubuntu":
#@   return "ubuntu-bionic"
#@ end
#@ end

#@ def validate_pr(distro):
name: #@ "prs-" + distro
public: true
serial: true
serial_groups:
- validate
plan:
- in_parallel:
  - get: resource-pr
    trigger: true
    version: every
  - get: #@ determine_base(distro)
    trigger: true
    params: {format: oci}
  - get: oci-build-task
  - #@ template.replace(extra_get_steps(distro))
- put: #@ resource_name + "-resource"
  resource: resource-pr
  params:
    context: #@ "status-" + distro
    path: resource-pr
    status: pending
  get_params:
    fetch_merge: true
- do:
  - #@ build_task(resource_name, distro)
  - #@ template.replace(extra_steps(distro))
  on_failure:
    put: resource-pr
    params:
      context: #@ "status-" + distro
      path: resource-pr
      status: failure
  on_success:
    put: resource-pr
    params:
      context: #@ "status-" + distro
      path: resource-pr
      status: success
#@ end


#@ def extra_get_steps(distro):
  #@ if resource_name == "cf":
- get: cf-cli
  trigger: true
  params: {globs: ["cf-cli*linux*"]}
  #@ elif resource_name == "concourse-pipeline":
- get: fly
  params: {globs: ["fly-*-linux-amd64.tgz"]}
  #@ else: return []
#@ end

#@ def publish_job(bump):
name: #@ "publish-" + bump
plan:
- in_parallel:
  - get: resource-repo
    passed:
    - build-alpine
    - build-ubuntu
  - get: ci
  - get: release-me
  - get: resource-image-dev-alpine
    passed: [build-alpine]
    params: {format: oci}
  - get: resource-image-dev-alpine-rootfs
    resource: resource-image-dev-alpine
    passed: [build-alpine]
    params: {format: rootfs}
  - get: resource-image-dev-ubuntu
    passed: [build-ubuntu]
    params: {format: oci}
  - get: resource-image-dev-ubuntu-rootfs
    resource: resource-image-dev-ubuntu
    passed: [build-ubuntu]
    params: {format: rootfs}
  - get: version
    params:
      bump: #@ bump
- task: create-release
  config:
    platform: linux
    image_resource:
      type: registry-image
      source:
        repository: ubuntu
    inputs:
    - name: version
    - name: resource-image-dev-alpine-rootfs
    - name: resource-image-dev-ubuntu-rootfs
    outputs:
    - name: release
    run:
      path: bash
      args:
      - "-exc"
      #@yaml/text-templated-strings
      - |
        cat <<EOF > resource_metadata.json
        {
          "type": "(@= resource_name @)",
          "version": "$(cat version/number)",
          "privileged": (@= str(privileged()).lower() @),
          "unique_version_history": (@= str(unique_version_history()).lower() @)
        }
        EOF

        version="$(cat version/number)"
        echo "v${version}" > release/name

        pushd resource-image-dev-alpine-rootfs
          cp ../resource_metadata.json .
          tar -czf rootfs.tgz -C rootfs .
          tar -czf ../release/(@= resource_name @)-resource-${version}-alpine.tgz rootfs.tgz resource_metadata.json
        popd

        pushd resource-image-dev-ubuntu-rootfs
          cp ../resource_metadata.json .
          tar -czf rootfs.tgz -C rootfs .
          tar -czf ../release/(@= resource_name @)-resource-${version}-ubuntu.tgz rootfs.tgz resource_metadata.json
        popd
- task: build-release-notes
  file: ci/tasks/build-release-notes.yml
  params:
    GITHUB_OWNER: concourse
    GITHUB_REPO: #@ resource_name + "-resource"
    GITHUB_TOKEN: ((concourse_github_dummy.access_token))
    GITHUB_BRANCH: master
  input_mapping:
    repo: resource-repo
- task: generate-dpkg-list
  image: resource-image-dev-ubuntu-rootfs
  config:
    platform: linux
    inputs:
    - name: version
    outputs:
    - name: dpkg-file
    run:
      path: bash
      args:
      - "-exc"
      #@yaml/text-templated-strings
      - |
        VERSION="$(cat version/number)"
        RESOURCE="(@= resource_name @)"
        DPKG_FILE="${RESOURCE}-dpkg-list-${VERSION}.txt"
        dpkg -l > "dpkg-file/${DPKG_FILE}"
- load_var: version
  file: version/version
- in_parallel:
  - put: resource-image
    params:
      image: resource-image-dev-alpine/image.tar
      version: ((.:version))
      bump_aliases: true
  - put: resource-image-alpine
    params:
      image: resource-image-dev-alpine/image.tar
      version: ((.:version))
      bump_aliases: true
  - put: resource-image-ubuntu
    params:
      image: resource-image-dev-ubuntu/image.tar
      version: ((.:version))
      bump_aliases: true
  - put: resource-repo-release
    params:
      commitish: resource-repo/.git/ref
      body: built-notes/notes.md
      globs:
      - release/*.tgz
      name: release/name
      tag: version/version
      tag_prefix: v
- put: dpkg-list-store
  params:
    file: #@ "dpkg-file/" + resource_name + "-dpkg-list-*.txt"
- put: version
  params:
    file: version/version
#@ end

#@ def unique_version_history():
#@ return resource_name == "time"
#@ end

#@ def privileged():
#@ return resource_name == "docker-image"
#@ end

---
jobs:
- #@ build_image("alpine")
- #@ build_image("ubuntu")
- #@ validate_pr("alpine")
- #@ validate_pr("ubuntu")
- #@ publish_job("major")
- #@ publish_job("minor")
- #@ publish_job("patch")

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: jtarchie/pr

- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource

- name: registry-image
  type: registry-image
  source:
    repository: concourse/registry-image-resource

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource


resources:
- name: alpine-edge
  type: registry-image
  icon: docker
  source:
    repository: alpine
    tag: edge

- name: ubuntu-bionic
  type: registry-image
  icon: docker
  source:
    repository: ubuntu
    tag: bionic

- name: resource-repo
  type: git
  icon: github
  source:
    branch: master
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:concourse/" + resource_name + "-resource"

- name: resource-repo-release
  type: github-release
  icon: package-variant-closed
  source:
    access_token: ((concourse_bot_access_token))
    owner: concourse
    repository: #@ resource_name + "-resource"

- name: version
  type: semver
  icon: tag
  source:
    branch: version
    driver: git
    file: version
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:concourse/" + resource_name + "-resource"

- name: resource-pr
  type: pull-request
  icon: source-pull
  source:
    access_token: ((pull_requests_access_token))
    base: master
    repo: #@ "concourse/" + resource_name + "-resource"

- name: resource-image
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    username: ((docker.username))
    password: ((docker.password))

- name: resource-image-alpine
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    variant: alpine
    username: ((docker.username))
    password: ((docker.password))

- name: resource-image-ubuntu
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    variant: ubuntu
    username: ((docker.username))
    password: ((docker.password))

- name: resource-image-dev-alpine
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    tag: dev
    password: ((docker.password))
    username: ((docker.username))

- name: resource-image-dev-ubuntu
  type: registry-image
  icon: docker
  source:
    password: ((docker.password))
    repository: #@ "concourse/" + resource_name + "-resource"
    tag: dev-ubuntu
    username: ((docker.username))

- name: dpkg-list-store
  type: gcs
  source:
    bucket: concourse-ubuntu-dpkg-list
    json_key: ((concourse_dpkg_list_json_key))
    regexp: #@ resource_name + "-dpkg-list-(.*).txt"

- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/ci.git
    branch: master

- name: release-me
  type: github-release
  icon: package-down
  source:
    owner: clarafu
    repository: release-me

- name: oci-build-task
  type: registry-image
  icon: docker
  source:
    repository: vito/oci-build-task

#@ if resource_name == "cf":
- name: cf-cli
  type: s3
  source:
    bucket: cf-cli-releases
    regexp: "releases/v([\\d\\.]+)/cf-cli_.*_linux_x86-64.tgz"
    region_name: us-west-1
#@ elif resource_name == "concourse-pipeline":
- name: fly
  type: github-release
  source:
    user: concourse
    repository: concourse
    access_token: ((concourse_github_dummy.access_token))
#@ end
