jobs:
- name: bosh-cleanup
  serial: true
  plan:
  - get: weekly
    trigger: true

  - task: cleanup
    attempts: 3
    params: &bosh-params
      BOSH_CA_CERT: ((bosh_ca_cert))
      BOSH_CLIENT: ((bosh_client.id))
      BOSH_CLIENT_SECRET: ((bosh_client.secret))
      BOSH_DEPLOYMENT: concourse-prod
      BOSH_ENVIRONMENT: ((bosh_target))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: concourse/unit}
      run:
        path: sh
        args:
        - -c
        - |
          bosh clean-up --all -n

resources:
- name: weekly
  type: time
  source:
    location: America/Toronto
    start: 12:00 AM
    stop: 1:00 AM
    days: [Saturday]

