---
resource_types:
- name: slack-notifier
  type: registry-image
  source: {repository: mockersf/concourse-slack-notifier}

resources:
- name: latest-scan-status
  type: git
  source:
    private_key: ((norsk_deploy_key))
    uri: git@github.com:pivotal/oslo-scan-status.git
    paths: [ p-concourse/* ]
- name: 4.2.x-scan-status
  type: git
  source:
    private_key: ((norsk_deploy_key))
    uri: git@github.com:pivotal/oslo-scan-status.git
    paths: [ p-concourse-4.2.x/* ]
- name: 5.5.x-scan-status
  type: git
  source:
    private_key: ((norsk_deploy_key))
    uri: git@github.com:pivotal/oslo-scan-status.git
    paths: [ p-concourse-5.5.x/* ]
- name: ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/ci.git
    branch: master
- name: notify
  type: slack-notifier
  icon: slack
  source:
    url: ((slack_hook))
    username: ((basic_auth.username))
    password: ((basic_auth.password))
    concourse_url: https://ci.concourse-ci.org

jobs:
- name: check-p-concourse-latest
  plan:
  - get: latest-scan-status
    trigger: true
  - get: ci
  - task: check-status-file
    file: ci/tasks/check-norsk-status.yml
    input_mapping: {scan-status: latest-scan-status}
  on_success:
    do:
    - task: format-slack-message
      file: ci/tasks/format-slack-message.yml
      input_mapping: {src: latest-scan-status}
      params:
        GITHUB_TOKEN: ((concourse_github_dummy.access_token))
        SLACK_TOKEN: ((slack_token))
    - put: notify
      params:
        message_file: message/message
        mode: normal
        alert_type: fixed
  on_failure:
    do:
    - task: format-slack-message
      file: ci/tasks/format-slack-message.yml
      input_mapping: {src: latest-scan-status}
      params:
        GITHUB_TOKEN: ((concourse_github_dummy.access_token))
        SLACK_TOKEN: ((slack_token))
    - put: notify
      params:
        message_file: message/message
        mode: normal
        alert_type: broke

- name: check-p-concourse-4.2.x
  plan:
  - get: 4.2.x-scan-status
    trigger: true
  - get: ci
  - task: check-status-file
    file: ci/tasks/check-norsk-status.yml
    input_mapping: {scan-status: 4.2.x-scan-status}
  on_success:
    do:
    - task: format-slack-message
      file: ci/tasks/format-slack-message.yml
      input_mapping: {src: 4.2.x-scan-status}
      params:
        GITHUB_TOKEN: ((concourse_github_dummy.access_token))
        SLACK_TOKEN: ((slack_token))
    - put: notify
      params:
        message_file: message/message
        mode: normal
        alert_type: fixed
  on_failure:
    do:
    - task: format-slack-message
      file: ci/tasks/format-slack-message.yml
      input_mapping: {src: 4.2.x-scan-status}
      params:
        GITHUB_TOKEN: ((concourse_github_dummy.access_token))
        SLACK_TOKEN: ((slack_token))
    - put: notify
      params:
        message_file: message/message
        mode: normal
        alert_type: broke

- name: check-p-concourse-5.5.x
  plan:
    - get: 5.5.x-scan-status
      trigger: true
    - get: ci
    - task: check-status-file
      file: ci/tasks/check-norsk-status.yml
      input_mapping: {scan-status: 5.5.x-scan-status}
  on_success:
    do:
      - task: format-slack-message
        file: ci/tasks/format-slack-message.yml
        input_mapping: {src: 5.5.x-scan-status}
        params:
          GITHUB_TOKEN: ((concourse_github_dummy.access_token))
          SLACK_TOKEN: ((slack_token))
      - put: notify
        params:
          message_file: message/message
          mode: normal
          alert_type: fixed
  on_failure:
    do:
      - task: format-slack-message
        file: ci/tasks/format-slack-message.yml
        input_mapping: {src: 5.5.x-scan-status}
        params:
          GITHUB_TOKEN: ((concourse_github_dummy.access_token))
          SLACK_TOKEN: ((slack_token))
      - put: notify
        params:
          message_file: message/message
          mode: normal
          alert_type: broke