resource_types:
- name: concourse-pipeline
  type: registry-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: pipelines
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/ci
    paths:
    - pipelines

- name: prod
  type: concourse-pipeline
  icon: pipe
  source:
    target: https://ci.concourse-ci.org
    teams:
    - name: main
      username: ((basic_auth.username))
      password: ((basic_auth.password))

jobs:
- name: reconfigure-pipelines
  plan:
  - get: pipelines
    trigger: true
  - put: prod
    params:
      pipelines:
      - name: prs
        team: main
        config_file: pipelines/pipelines/prs.yml
      - name: release-5.2.x
        team: main
        config_file: pipelines/pipelines/release.yml
        vars:
          release_major: "5"
          release_minor: "5.2"
          concourse_smoke_deployment_name: "concourse-smoke-5-2"
      - name: release-5.3.x
        team: main
        config_file: pipelines/pipelines/release.yml
        vars:
          release_major: "5"
          release_minor: "5.3"
          concourse_smoke_deployment_name: "concourse-smoke-5-3"
      - name: concourse
        team: main
        config_file: pipelines/pipelines/concourse.yml
