resource_types:
- name: slack-notifier
  type: registry-image
  source: {repository: mockersf/concourse-slack-notifier}

resources:
- name: pipelines-and-tasks
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/ci
    paths:
    - pipelines
    - tasks

- name: baggageclaim-ci
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/baggageclaim
    paths: [ci]

- name: concourse-for-k8s
  type: git
  icon: github
  source:
    uri: git@github.com:pivotal/concourse-for-k8s.git
    private_key: ((concourse_for_k8s_token))
    paths:
    - ci

- name: concourse-for-platform-automation
  type: git
  icon: github
  source:
    uri: https://github.com/pivotal/concourse-for-platform-automation.git

- name: docs-ci
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/docs
    paths: [ci]

- name: flight-attendant-ci
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/flight-attendant
    paths:
    - ci

- name: ft-ci
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/ft
    paths:
    - ci

- name: resource-types-website-ci
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/resource-types-website
    paths: [ci]

- name: boarding-pass-ci
  type: git
  icon: github
  source:
    uri: git@github.com:concourse/boarding-pass.git
    paths: [ci]
    private_key: ((concourse_bot_private_key))

- name: ruby-alpine-image
  type: registry-image
  source:
    repository: ruby
    tag: rc-alpine

- name: oxygen-mask
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/oxygen-mask

- name: examples
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/examples
    paths: [pipelines]

- name: notify
  type: slack-notifier
  icon: slack
  source:
    url: ((slack_hook))

- name: latest-concourse
  type: github-release
  source:
    owner: concourse
    repository: concourse
    access_token: ((concourse_github_release.access_token))

jobs:
- name: reconfigure-self
  plan:
  - get: pipelines-and-tasks
    trigger: true
  - set_pipeline: reconfigure-pipelines
    file: pipelines-and-tasks/pipelines/reconfigure.yml

- name: reconfigure-promote
  plan:
  - get: pipelines-and-tasks
    trigger: true
    passed: [reconfigure-self]
  - get: latest-concourse
    trigger: true
  # - load_var: release-version
  #   file: latest-concourse/version
  #
  # workaround for https://github.com/concourse/concourse/issues/5709
  - task: prep-var-files
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: ubuntu}

      inputs:
      - name: latest-concourse

      outputs:
      - name: vars

      run:
        path: bash
        args:
        - -exc
        - |
          echo "release_version: $(cat latest-concourse/version)" >> vars/vars.yml
  - set_pipeline: promote
    file: pipelines-and-tasks/pipelines/promote.yml
    var_files:
    - vars/vars.yml

- name: reconfigure-resource-pipelines
  plan:
  - get: pipelines-and-tasks
    trigger: true
    passed: [reconfigure-self]
  - task: render-resource-templates
    file: pipelines-and-tasks/tasks/render-resource-pipeline-templates.yml
    params:
      RESOURCES: |
        git
        time
        docker-image
        registry-image
        cf
        bosh-io-release
        bosh-io-stemcell
        tracker
        hg
        github-release
        semver
        s3
        pool
        datadog-event
        mock
    input_mapping: {pipelines: pipelines-and-tasks}
  - in_parallel:
    - set_pipeline: resource
      instance_vars: {type: git}
      file: rendered_pipelines/git.yml
    - set_pipeline: resource
      instance_vars: {type: time}
      file: rendered_pipelines/time.yml
    - set_pipeline: resource
      instance_vars: {type: docker-image}
      file: rendered_pipelines/docker-image.yml
    - set_pipeline: resource
      instance_vars: {type: registry-image}
      file: rendered_pipelines/registry-image.yml
    - set_pipeline: resource
      instance_vars: {type: cf}
      file: rendered_pipelines/cf.yml
    - set_pipeline: resource
      instance_vars: {type: bosh-io-release}
      file: rendered_pipelines/bosh-io-release.yml
    - set_pipeline: resource
      instance_vars: {type: bosh-io-stemcell}
      file: rendered_pipelines/bosh-io-stemcell.yml
    - set_pipeline: resource
      instance_vars: {type: tracker}
      file: rendered_pipelines/tracker.yml
    - set_pipeline: resource
      instance_vars: {type: hg}
      file: rendered_pipelines/hg.yml
    - set_pipeline: resource
      instance_vars: {type: github-release}
      file: rendered_pipelines/github-release.yml
    - set_pipeline: resource
      instance_vars: {type: semver}
      file: rendered_pipelines/semver.yml
    - set_pipeline: resource
      instance_vars: {type: s3}
      file: rendered_pipelines/s3.yml
    - set_pipeline: resource
      instance_vars: {type: pool}
      file: rendered_pipelines/pool.yml
    - set_pipeline: resource
      instance_vars: {type: datadog-event}
      file: rendered_pipelines/datadog-event.yml
    - set_pipeline: resource
      instance_vars: {type: mock}
      file: rendered_pipelines/mock.yml

- name: reconfigure-platform-automation
  plan:
  - get: pipelines-and-tasks
    passed: [reconfigure-self]
    trigger: true
  - get: concourse-for-platform-automation
    trigger: true
  - task: render-platform-automation
    params:
      PIPELINES: pipeline.yml
    input_mapping: {pipelines: concourse-for-platform-automation}
    file: pipelines-and-tasks/tasks/render-ytt.yml
  - set_pipeline: enterprise-platform-automation
    file: rendered_pipelines/pipeline.yml

- name: unit
  plan:
  - get: pipelines-and-tasks
    trigger: true
    passed: [reconfigure-self]
  - task: unit
    file: pipelines-and-tasks/tasks/ci-unit.yml
    input_mapping: {ci: pipelines-and-tasks}
  on_failure: &notify
    put: notify
    params:
      mode: normal
      alert_type: failed

- name: reconfigure-pipelines
  plan:
  - get: pipelines-and-tasks
    trigger: true
    passed: [unit]
  - get: baggageclaim-ci
    trigger: true
  - get: concourse-for-k8s
    trigger: true
  - get: docs-ci
    trigger: true
  - get: flight-attendant-ci
    trigger: true
  - get: ft-ci
    trigger: true
  - get: resource-types-website-ci
    trigger: true
  - get: boarding-pass-ci
    trigger: true
  - set_pipeline: concourse
    file: pipelines-and-tasks/pipelines/concourse.yml
  - set_pipeline: helm-chart
    file: pipelines-and-tasks/pipelines/helm-chart.yml
  - set_pipeline: prs
    team: contributor
    file: pipelines-and-tasks/pipelines/prs.yml
    instance_vars:
      branch: master
    vars:
      dev_image_tag: latest
      concourse_image_tag: latest
  - set_pipeline: helm-prs
    file: pipelines-and-tasks/pipelines/helm-prs.yml
    vars:
      pr_base_branch: master
      concourse_base_branch: master
      concourse_image_name: concourse/concourse
      concourse_image_tag: latest
  - set_pipeline: helm-prs-dev
    file: pipelines-and-tasks/pipelines/helm-prs.yml
    vars:
      pr_base_branch: dev
      concourse_base_branch: master
      concourse_image_name: concourse/concourse-rc
      concourse_image_tag: latest
  - set_pipeline: baggageclaim
    file: baggageclaim-ci/ci/pipeline.yml
  - set_pipeline: baggageclaim-prs
    team: contributor
    file: baggageclaim-ci/ci/prs-pipeline.yml
  - set_pipeline: docs-prs
    team: contributor
    file: docs-ci/ci/prs-pipeline.yml
  - set_pipeline: dutyfree
    team: dutyfree
    file: resource-types-website-ci/ci/pipeline.yml
  - set_pipeline: bosh-cleanup
    file: pipelines-and-tasks/pipelines/bosh-cleanup.yml
  - set_pipeline: norsk-mirror
    file: pipelines-and-tasks/pipelines/norsk-mirror.yml
  - set_pipeline: release-6.3.x
    file: pipelines-and-tasks/pipelines/release.yml
    vars:
      release_major: "6"
      release_minor: "6.3"
      latest_release: "6.2"
      concourse_smoke_deployment_name: "concourse-smoke-6-3"
      has_runtime_flag: "false"
      helm_version: "2" # tech-debt for this pipeline only
      slack_hook: ((slack_hooks.concourse-private))
  - set_pipeline: release-6.7.x
    file: pipelines-and-tasks/pipelines/release.yml
    vars:
      release_major: "6"
      release_minor: "6.7"
      latest_release: "6.6"
      concourse_smoke_deployment_name: "concourse-smoke-6-7"
      has_runtime_flag: "true"
      helm_version: "3"
      slack_hook: ((slack_hooks.concourse-private))
  - set_pipeline: enterprise-helm-chart
    file: concourse-for-k8s/ci/pipeline.yml
    vars:
      concourse_chart_branch: release/6.7.x
      concourse_minor: "6.7.3"
  - set_pipeline: datadog-dashboards
    file: pipelines-and-tasks/pipelines/datadog-dashboards.yml
  - set_pipeline: flight-attendant
    file: flight-attendant-ci/ci/pipeline.yml
  - set_pipeline: ft
    file: ft-ci/ci/pipeline.yml
  - set_pipeline: boarding-pass
    file: boarding-pass-ci/ci/pipeline.yml
  - set_pipeline: monitor-ci-memory
    file: pipelines-and-tasks/pipelines/monitor-ci-memory.yml
  on_failure: *notify
  on_error: *notify

- name: reconfigure-monitoring-pipeline
  plan:
  - get: pipelines-and-tasks
    passed: [reconfigure-self]
  - get: oxygen-mask
    trigger: true
  - get: ruby-alpine-image
  - task: generate-monitor-yml
    image: ruby-alpine-image
    config:
      platform: linux
      inputs:
      - name: oxygen-mask
      outputs:
      - name: oxygen-mask
      run:
        dir: oxygen-mask
        path: sh
        args:
        - -c
        - |
          erb monitor.yml > gen-monitor.yml
  - set_pipeline: monitoring-stats
    file: oxygen-mask/gen-monitor.yml
    vars:
      atc_url: https://hush-house.pivotal.io
      interval: 30s
      username: ((basic_auth.username))
      password: ((basic_auth.password))
      team_name: main
      pipeline_name: monitoring
      datadog_api_key: ((datadog_api_key))
      github_access_token: ((concourse_github_dummy.access_token))

- name: reconfigure-example-pipelines
  plan:
  - get: pipelines-and-tasks
    passed: [reconfigure-self]
  - get: examples
    trigger: true
  - set_pipeline: set-pipelines
    team: examples
    file: examples/pipelines/set-pipelines.yml
