resource_types:
- name: concourse-pipeline
  type: registry-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: pipelines
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/ci
    paths:
    - pipelines

- name: charts-maintenance
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/charts
    branch: maintenance

- name: maintenance-image
  type: registry-image
  source:
    password: ((docker.password))
    repository: concourse/charts-maintenance
    username: ((docker.username))

- name: prod
  type: concourse-pipeline
  icon: pipe
  source:
    target: https://ci.concourse-ci.org
    teams:
    - name: main
      username: ((basic_auth.username))
      password: ((basic_auth.password))

jobs:
- name: reconfigure-pipelines
  plan:
  - get: pipelines
    trigger: true
  - get: charts-maintenance
    trigger: true
  - get: maintenance-image
  - task: generate-charts-yaml
    image: maintenance-image
    config:
      platform: linux
      inputs:
      - name: charts-maintenance
      outputs:
      - name: charts-maintenance
      run:
        dir: charts-maintenance
        path: make
        args: [pipeline.yml]
  - put: prod
    params:
      pipelines:
      - name: reconfigure-pipelines
        team: main
        config_file: pipelines/pipelines/reconfigure.yml
      - name: prs
        team: main
        config_file: pipelines/pipelines/prs.yml
      - name: wings
        team: main
        config_file: pipelines/pipelines/wings.yml
      - name: release-5.2.x
        team: main
        config_file: pipelines/pipelines/release.yml
        vars:
          release_major: "5"
          release_minor: "5.2"
          concourse_smoke_deployment_name: "concourse-smoke-5-2"
          use_external_linker: true
      - name: release-5.3.x
        team: main
        config_file: pipelines/pipelines/release.yml
        vars:
          release_major: "5"
          release_minor: "5.3"
          concourse_smoke_deployment_name: "concourse-smoke-5-3"
          use_external_linker: true
      - name: release-5.4.x
        team: main
        config_file: pipelines/pipelines/release.yml
        vars:
          release_major: "5"
          release_minor: "5.4"
          concourse_smoke_deployment_name: "concourse-smoke-5-4"
          use_external_linker: false
      - name: concourse
        team: main
        config_file: pipelines/pipelines/concourse.yml
      - name: concourse-charts
        team: main
        config_file: charts-maintenance/pipeline.yml
      - name: algorithm-v3
        team: main
        config_file: pipelines/pipelines/branch.yml
        vars:
          branch_name: algorithm-v3
          environment: algorithm
      - name: runtime-drills
        team: main
        config_file: pipelines/pipelines/branch.yml
        vars:
          branch_name: master
          environment: runtime-drills
      - name: set-zstd-drills-env
        team: main
        config_file: pipelines/pipelines/branch.yml
        vars:
          branch_name: use_zstd
          environment: use-zstd
      - name: lidar-drills
        team: main
        config_file: pipelines/pipelines/drills.yml
        vars:
          branch_name: checks
          environment: lidar-drills
      - name: prod-db-backup
        team: main
        config_file: pipelines/pipelines/bbr-backup.yml
      - name: bbr-restore-verify
        team: main
        config_file: pipelines/pipelines/bbr-restore-verify.yml
