resources:
#  - name: dex-github-release
#    type: github-release
#    icon: &release-icon package-variant-closed
#    access_token: ((concourse_github_release.access_token))

  - name: concourse-dex
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/dex
      branch: maintenance

  - name: ci
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/ci
      branch: upstream-dex-update

jobs:
  - name: update-prs
    plan:
      - in_parallel:
#          - get: dex-github-release
#            trigger: true
          - get: concourse-dex
          - get: ci
      - task: rebase-and-push
        file: ci/tasks/rebase-and-push-dex-prs.yml