---
resources:
- name: test-resource
  type: mock
  source: {mirror_self: true}

- name: test-image
  type: registry-image
  icon: docker
  source:
    repository: ubuntu

jobs:
- name: test-job
  plan:
  - get: test-resource
  - get: test-image
  - task: test-task
    image: test-image
    config:
      platform: linux

      run:
        path: bash
        args:
        - -exc
        - |
          echo hello
