---
resources:
- name: test-resource
  type: mock
  source: {mirror_self: true}

jobs:
- name: test-job
  plan:
  - get: test-resource
  - task: test-task
    image: test-resource
    config:
      platform: linux

      run:
        path: echo
        args: [hello]
